### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fancnc** [Holdi601/JoystickProfiler#6] opened 2021-03-29 18:40 UTC
Crashed as it opened main screen, no error code.

**Comment by Holdi601** [comment] 2021-03-29 18:41
Can you upload it Exception.zip file?
And can you try to restart, but delete before in your Documents folder the JoyPro folder (as there is some meta data and it might got corrupted)?

**Comment by Holdi601** [comment] 2021-03-29 19:13
There should be an exception.zip in your folder based on the crash please upload that :)

**Comment by fancnc** [comment] 2021-03-30 00:31
File requested
[Exception_132615166979732007.zip](https://github.com/Holdi601/JoystickProfiler/files/6225323/Exception_132615166979732007.zip)

**Comment by deejaylg** [comment] 2021-03-30 00:56
Hi! similar issue just after selecting the title from the first drop-down menu, or settings button.
[Exception_132615389700676343.zip](https://github.com/Holdi601/JoystickProfiler/files/6225401/Exception_132615389700676343.zip)

**Comment by fancnc** [comment] 2021-03-30 03:04
Not sure what happened, tried it again and working,

**Comment by Holdi601** [comment] 2021-03-30 13:11
It is fixed for next release. Dont worry :) The issue is, that it tries to read the local defaults and for that it needs to know where the DCS installation and for that it looks that up in registry. So it checks for the path of open beta and regular path, but here comes in where i mistyped. I mistyped one of the registry keys so if Open Beta or the Regular version could not be found that it crashes. But yeah that is fixed for next release.

**Comment by Holdi601** [comment] 2021-03-30 13:12
New version should be end of today, once im done with my dayjob and can fix another bug and then push a new version. If you need to something super immediatly use v28 in between as it has not this local read feature yet.

**Comment by Holdi601** [comment] 2021-03-30 22:07
Closing as v31 is published. Please reopen if other issues come up.

**Closed as completed by Holdi601** 2021-03-30 22:07 UTC
